name: weather_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  dartz: ^0.10.1
  kt_dart: ^1.1.0
  equatable: ^2.0.5
  injectable: ^2.1.2
  get_it: ^7.6.0
  dio: ^5.3.0
  geolocator: ^9.0.2
  flutter_bloc: ^8.1.3
  auto_route: ^7.7.1
  flutter_hooks: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  injectable_generator: ^2.1.6
  auto_route_generator: ^7.2.0

flutter:
  uses-material-design: true
